### ISSUE TITLE
IDA: Biodiversity

### ISSUE THREAD

**Issue by patrick-project-review** [BigDataKatha/intro-data-capstone-biodiversity#1]
Overall, great job! I didn't notice any issues with your presentation, it was very well put-together; the figures were easy to read and understand and I appreciate that you had them at the end of the presentation. Your code was also very clean and concise. The only suggestion I have is that if you have a line of code that is getting a little long (say longer than 80 characters), is to space it out with newlines like so:
```
protection_counts = species.groupby('conservation_status')
    .scientific_name
    .count()
    .reset_index() 
    .sort_values(by='scientific_name')
```

Though this line had some weird spacing so perhaps you did space it out and something weird happened when the file was converted from a Jupyter notebook.

**Comment by BigDataKatha** [comment]
Thank you for your feedback!
